### ISSUE TITLE
Add UniTask.OpenMod support

### ISSUE THREAD

**Issue by mkspeed0** [RocketModFix/RocketModFix#25]
Add support for UniTask.OpenMod with intialization in RocketMod subloading.

**Comment by sunnamed434** [comment]
Yes, it can be helpful because not everyone knows that to use UniTask, you just need to do some Initializations, on the other hand, we will be dependent on UniTask.OpenMod and the devs can add anything there, so we will gonna need to make our own fork and support it

If someone really wants to use UniTask they can just use the OpenMod module or use `RocketPluginHelper` NuGet/lib to initialize the UniTask, or just copy the initialize method into their plugin and check whether OpenMod is not loaded then just initialize it

**Comment by Jdance-Media** [comment]
Agreed,  support for UniTask.OpenMod should not be implemented.
