### ISSUE TITLE
Two small questions about plugins

### ISSUE THREAD

**Issue by d3adwolf** [RocketModFix/RocketModFix#37]
Thanks so much more for the work you do!

1. Please tell me, is it possible to build this functionality into the kernel, or somehow fix it from the kernel side?
https://github.com/ImperialPlugins/UnturnedProfiler/issues/1

2. It is also not clear whether it makes sense to limit the server FPS for better performance through the FPSCap plugin. Generally there is a line `<MaxFrames>60</MaxFrames>` in `serverfiles/Servers/Prod_Test/Rocket/Rocket.config.xml`, maybe this is enough.
https://github.com/cartman-2000/FPSCap/issues/3

**Comment by d3adwolf** [comment]
SOD's servers generally use 50FPS, how critical is that, what does it affect?

**Comment by sunnamed434** [comment]
FPS Lock (in this case you sent me the repos and I checked the code), well (see [here](https://github.com/cartman-2000/FPSCap/blob/master/CommandLimitTPS.cs#L56)), it simply changes UnityEngine.Application.targetFrameRate = `some TPS or in simple words FPS`

I had some time when I was working with Unity mobile game, iirc UnityEngine.Application.targetFrameRate just locks the FPS in-game (in this case on the Server)

If you check how `UnityEngine.Application.targetFrameRate` works you will see that it just changes the FPS (so Physics, for example, Update FixedUpdate will be a bit slower), I guess players will feel that very well, for example, if you played some games like Fortnite you probably saw that when a lot of buildings or players around you, you feel like laggy, very slow, you can't feel the game (it also affect on server FPS, because it handles a lot of things at the same time).

I don't think it's a good idea to even touch the TPS, because in Unturned everything is slow yet due to a lot of fixedupdates and updates, and you want to set it as 50, it will be even worse, as a solution don't change this property and try to don't use in the plugins (or plugins by other devs) which use fixedupdate or update, run another thread in a thread pool (Task.Run or use UniTask), if you call some Unturned's code return back to the main thread (UniTask.SwitchToMainThread), and do all the things optimized

**Comment by d3adwolf** [comment]
Got it, thanks for the reply! Is it possible to do something with UnturnedProfiler in the future?

**Comment by sunnamed434** [comment]
Do you mean you want to integrate the profiler into RocketModFix?

**Comment by d3adwolf** [comment]
Yes, or if possible just fix the current one, for it doesn't work and the error is in the issue above.

**Comment by d3adwolf** [comment]
> Да, или если есть возможность, то исправьте текущую, ибо она не работает и ошибка в вопросе выше.

https://github.com/ImperialPlugins/UnturnedProfiler/issues/1

**Comment by sunnamed434** [comment]
I checked the profiler code, I guess it is more of a problem due to outdated Redist (libs), or probably Mono's old API usage, and so on

If someone is ready can fix it of course, but I don't have time now for it, but if I'm free, I can do that why not, I see it very useful in my own projects
