### ISSUE TITLE
Add try catch blocks in the CommandRocket

### ISSUE THREAD

**Issue by sunnamed434** [RocketModFix/RocketModFix#45]
Right now if inside of the UnloadPlugin/LoadPlugin/ReloadPlugin was an error caller won't know what just happened, only the console

**Comment by Jdance-Media** [comment]
Honestly the whole loading command system is a bit dicey at best. A lot of plugins do not properly implement loading and unloading, and lot of crap isn't truly disposed. Either making a framework so that plugin developers can conform to an unloading/reloading standard or just making the system deprecated would be best.

**Comment by sunnamed434** [comment]
I agree the load/unload/reload is a bit dicey and this command must be used so carefully, if think from where that problem comes is people either want to update config or just unload the plugin (since it causes some problems like ping lags etc)

I'll stay anyway on adding try catch to that command

**Comment by Jdance-Media** [comment]
I don't disagree with the issue, just figured I should put out there that the whole system is screwed up.

**Comment by sunnamed434** [comment]
Ok, I got you
