### ISSUE TITLE
fix Rocket.Unturned.Player.Reputation.set

### ISSUE THREAD

**Issue by MrRousek** [RocketModFix/RocketModFix#80]
![image](https://github.com/RocketModFix/RocketModFix/assets/105581272/9843d84c-2a1f-4644-aa76-f0bb9b9b4ad1)
![image](https://github.com/RocketModFix/RocketModFix/assets/105581272/a0ce6df6-d303-4d86-8af9-6ad196e01b4b)

tell me your opinion, because this fix may break plugins

**Comment by Jdance-Media** [comment]
Uh, if it has been like that forever, I'd just keep it that way.

**Comment by sunnamed434** [comment]
Jdance comment answers it very well.

Player reputation was 5 before 
Player.Reputation = 5
But actually we don't get 5,we get 10, it might make a dev really confused. 

I agree that a lot of stuff must be deprecated in UnturnedPlayer (for example SteamProfile, and explain that it should be parsed manually). 

I'd recommend to use usual Player instead, same with events, as it more stable rather than doing it via Rocket, however sometimes UnturnedPlayerComponent, UnturnedPlayer, and Rocket events are useful, because it's binded to Unity (MonoBehavior), Update/Start methods etc.

Closing it.
